# Generated by Django 5.1.1 on 2024-10-01 01:01

from django.db import migrations

def populate_class_years(apps, schema_editor):
    # Get the ClassYear model
    ClassYear = apps.get_model('api', 'ClassYear')

    # Define the class years you want to populate
    class_years = [
        ('Year 1', 'Description for year 1'),
        ('Year 2', 'Description for Year 2'),
        ('Year 3', 'Description for Year 3'),
        ('Year 4', 'Description for Year 4'),
        ('Year 5', 'Description for Year 5'),
        ('Year 6', 'Description for Year 6'),
    ]

    # Bulk create the class years
    for name, description in class_years:
        ClassYear.objects.create(name=name, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_class_years),
    ]