# Generated by Django 5.1.1 on 2024-10-01 01:01

from django.db import migrations, connection

def populate_class_years(apps, schema_editor):
    # Get the ClassYear model
    ClassYear = apps.get_model('api', 'ClassYear')

    # Define the class years you want to populate
    class_years = [
        ('Year 1', 'Description for year 1'),
        ('Year 2', 'Description for Year 2'),
        ('Year 3', 'Description for Year 3'),
        ('Year 4', 'Description for Year 4'),
        ('Year 5', 'Description for Year 5'),
        ('Year 6', 'Description for Year 6'),
    ]

    # Bulk create the class years
    for name, description in class_years:
        ClassYear.objects.create(name=name, description=description)

def reverse_populate_class_years(apps, schema_editor):
    # Get the ClassYear model
    ClassYear = apps.get_model('api', 'ClassYear')

    # Define the class year names to delete
    class_year_names = [
        'Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6'
    ]

    # Delete the populated class years
    ClassYear.objects.filter(name__in=class_year_names).delete()

    # Reset the primary key sequence for the ClassYear table
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute("DELETE FROM sqlite_sequence WHERE name='api_classyear';")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_class_years, reverse_populate_class_years),
    ]