# Generated by Django 5.1.1 on 2024-10-01 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gamesession_correct_answers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='user',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='student',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
