# Generated by Django 5.1.1 on 2024-10-01 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_gamesession_user_gamesession_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
