# Generated by Django 5.1.1 on 2024-10-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_load_dummy_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
